  last_name  | last_name_count 
-------------+-----------------
 KILMER      |               5
 NOLTE       |               4
 TEMPLE      |               4
 TORN        |               3
 HOPKINS     |               3
 ALLEN       |               3
 ZELLWEGER   |               3
 WILLIAMS    |               3
 PECK        |               3
 WILLIS      |               3
 JOHANSSON   |               3
 HOFFMAN     |               3
 HARRIS      |               3
 AKROYD      |               3
 DAVIS       |               3
 GUINESS     |               3
 DEGENERES   |               3
 BERRY       |               3
 KEITEL      |               3
 GARLAND     |               3
 DUKAKIS     |               2
 DEE         |               2
 CAGE        |               2
 BRODY       |               2
 PENN        |               2
 MCCONAUGHEY |               2
 BAILEY      |               2
 PALTROW     |               2
 CRONYN      |               2
 HOPPER      |               2
 TRACY       |               2
 WAHLBERG    |               2
 DEAN        |               2
 BOLGER      |               2
 HACKMAN     |               2
 MCKELLEN    |               2
 MONROE      |               2
 SILVERSTONE |               2
 MOSTEL      |               2
 MCQUEEN     |               2
 WOOD        |               2
 GOODING     |               2
 OLIVIER     |               2
 DEPP        |               2
 WEST        |               2
 BENING      |               2
 DENCH       |               2
 NEESON      |               2
 STREEP      |               2
 WINSLET     |               2
 CHASE       |               2
 TANDY       |               2
 CRAWFORD    |               2
 FAWCETT     |               2
 JACKMAN     |               2
(55 rows)
