  last_name   | last_name_count 
--------------+-----------------
 KILMER       |               5
 TEMPLE       |               4
 NOLTE        |               4
 WILLIAMS     |               3
 PECK         |               3
 HOPKINS      |               3
 DAVIS        |               3
 HARRIS       |               3
 DEGENERES    |               3
 HOFFMAN      |               3
 GARLAND      |               3
 BERRY        |               3
 KEITEL       |               3
 TORN         |               3
 GUINESS      |               3
 JOHANSSON    |               3
 ZELLWEGER    |               3
 AKROYD       |               3
 WILLIS       |               3
 ALLEN        |               3
 CRONYN       |               2
 DEPP         |               2
 JACKMAN      |               2
 HOPPER       |               2
 DUKAKIS      |               2
 TRACY        |               2
 MONROE       |               2
 MOSTEL       |               2
 MCKELLEN     |               2
 WAHLBERG     |               2
 DEAN         |               2
 BENING       |               2
 SILVERSTONE  |               2
 WEST         |               2
 HACKMAN      |               2
 BOLGER       |               2
 DEE          |               2
 MCQUEEN      |               2
 DENCH        |               2
 NEESON       |               2
 STREEP       |               2
 CAGE         |               2
 BRODY        |               2
 WINSLET      |               2
 WOOD         |               2
 GOODING      |               2
 PENN         |               2
 MCCONAUGHEY  |               2
 CHASE        |               2
 BAILEY       |               2
 PALTROW      |               2
 TANDY        |               2
 CRAWFORD     |               2
 FAWCETT      |               2
 OLIVIER      |               2
 CARREY       |               1
 JOLIE        |               1
 TOMEI        |               1
 BACALL       |               1
 PESCI        |               1
 TAUTOU       |               1
 LEIGH        |               1
 COSTNER      |               1
 WITHERSPOON  |               1
 BASINGER     |               1
 PITT         |               1
 WILSON       |               1
 BRIDGES      |               1
 HUNT         |               1
 GIBSON       |               1
 SUVARI       |               1
 HESTON       |               1
 SINATRA      |               1
 ASTAIRE      |               1
 BULLOCK      |               1
 JOVOVICH     |               1
 GABLE        |               1
 MALDEN       |               1
 CHAPLIN      |               1
 MANSFIELD    |               1
 HURT         |               1
 MCDORMAND    |               1
 BALL         |               1
 PRESLEY      |               1
 RYDER        |               1
 BIRCH        |               1
 WALKEN       |               1
 BERGMAN      |               1
 HOPE         |               1
 CRUZ         |               1
 BERGEN       |               1
 NICHOLSON    |               1
 PHOENIX      |               1
 PFEIFFER     |               1
 SWANK        |               1
 STALLONE     |               1
 BLOOM        |               1
 GRANT        |               1
 SOBIESKI     |               1
 CRUISE       |               1
 BARRYMORE    |               1
 BALE         |               1
 CROWE        |               1
 DAY-LEWIS    |               1
 WAYNE        |               1
 LOLLOBRIGIDA |               1
 HAWKE        |               1
 MARX         |               1
 DUNST        |               1
 POSEY        |               1
 DAMON        |               1
 PINKETT      |               1
 VOIGHT       |               1
 DERN         |               1
 MIRANDA      |               1
 REYNOLDS     |               1
 GOLDBERG     |               1
 HUDSON       |               1
 DREYFUSS     |               1
 WRAY         |               1
 CLOSE        |               1
(121 rows)
