            title            | film_id | actor_count 
-----------------------------+---------+-------------
 BAKED CLEOPATRA             |      50 |           1
 BRIDE INTRIGUE              |      97 |           1
 DOLLS RAGE                  |     240 |           1
 DWARFS ALTER                |     264 |           1
 FERRIS MOTHER               |     308 |           1
 FOREVER CANDIDATE           |     328 |           1
 GHOSTBUSTERS ELF            |     355 |           1
 GIANT TROOPERS              |     356 |           1
 HUNGER ROOF                 |     440 |           1
 LOLITA WORLD                |     528 |           1
 MALTESE HOPE                |     556 |           1
 MINORITY KISS               |     581 |           1
 MIRACLE VIRTUAL             |     582 |           1
 MOON BUNCH                  |     595 |           1
 MUSKETEERS WAIT             |     611 |           1
 PACKER MADIGAN              |     651 |           1
 PIRATES ROXANNE             |     681 |           1
 PSYCHO SHRUNK               |     701 |           1
 SHOCK CABIN                 |     789 |           1
 STONE FIRE                  |     848 |           1
 YENTL IDAHO                 |     995 |           1
 ANTHEM LUKE                 |      28 |           2
 BIKINI BORROWERS            |      70 |           2
 BIRD INDEPENDENCE           |      75 |           2
 BOUND CHEAPER               |      91 |           2
 BRANNIGAN SUNRISE           |      93 |           2
 BRINGING HYSTERICAL         |      99 |           2
 BUGSY SONG                  |     104 |           2
 CALIFORNIA BIRDS            |     113 |           2
 CAMELOT VACATION            |     114 |           2
 CHAINSAW UPTOWN             |     132 |           2
 CHARIOTS CONSPIRACY         |     138 |           2
 CHEAPER CLYDE               |     140 |           2
 CHICKEN HELLFIGHTERS        |     142 |           2
 CIRCUS YOUTH                |     152 |           2
 CONFIDENTIAL INTERVIEW      |     174 |           2
 CROSSING DIVORCE            |     192 |           2
 CRUELTY UNFORGIVEN          |     196 |           2
 DARKNESS WAR                |     209 |           2
 DARLING BREAKING            |     211 |           2
 DETAILS PACKER              |     227 |           2
 DUCK RACER                  |     259 |           2
 DYING MAKER                 |     265 |           2
 FISH OPUS                   |     319 |           2
 FOOL MOCKINGBIRD            |     327 |           2
 FRANKENSTEIN STRANGER       |     332 |           2
 GOLD RIVER                  |     365 |           2
 GRADUATE LORD               |     373 |           2
 HEAD STRANGER               |     408 |           2
 HOLLOW JEOPARDY             |     422 |           2
 HUNCHBACK IMPOSSIBLE        |     439 |           2
 INTENTIONS EMPIRE           |     464 |           2
 ITALIAN AFRICAN             |     472 |           2
 JINGLE SAGEBRUSH            |     487 |           2
 JOON NORTHWEST              |     488 |           2
 LAWRENCE LOVE               |     511 |           2
 LIGHTS DEER                 |     523 |           2
 LOCK REAR                   |     526 |           2
 MANCHURIAN CURTAIN          |     557 |           2
 MENAGERIE RUSHMORE          |     569 |           2
 MIDSUMMER GROUNDHOG         |     575 |           2
 MINE TITANS                 |     580 |           2
 MONTEZUMA COMMAND           |     594 |           2
 NIGHTMARE CHILL             |     624 |           2
 NOTORIOUS REUNION           |     629 |           2
 NOTTING SPEAKEASY           |     630 |           2
 NUTS TIES                   |     632 |           2
 PARTY KNOCK                 |     660 |           2
 PHANTOM GLORY               |     675 |           2
 PHILADELPHIA WIFE           |     676 |           2
 PURE RUNNER                 |     704 |           2
 ROBBERY BRIGHT              |     736 |           2
 ROMAN PUNK                  |     741 |           2
 ROOM ROMAN                  |     743 |           2
 SAMURAI LION                |     760 |           2
 SATURN NAME                 |     765 |           2
 SHOW LORD                   |     791 |           2
 SMOOCHY CONTROL             |     813 |           2
 SOUP WISDOM                 |     822 |           2
 SOUTH WAIT                  |     823 |           2
 STAGE WORLD                 |     837 |           2
 TERMINATOR CLUB             |     884 |           2
 THIN SAGEBRUSH              |     888 |           2
 VALENTINE VANISHING         |     931 |           2
 VANILLA DAY                 |     934 |           2
 VANISHED GARDEN             |     935 |           2
 VIETNAM SMOOCHY             |     942 |           2
 VILLAIN DESPERATE           |     943 |           2
 WILLOW TRACY                |     975 |           2
 WONKA SEA                   |     986 |           2
 ANNIE IDENTITY              |      26 |           3
 ANYTHING SAVANNAH           |      30 |           3
 ARK RIDGEMONT               |      38 |           3
 ARSENIC INDEPENDENCE        |      41 |           3
 AUTUMN CROW                 |      46 |           3
 BEAR GRACELAND              |      59 |           3
 BILKO ANONYMOUS             |      71 |           3
 BLINDNESS GUN               |      81 |           3
 BUBBLE GROSSE               |     102 |           3
 BUTCH PANTHER               |     108 |           3
 CAMPUS REMEMBER             |     115 |           3
 CHARADE DUFFEL              |     137 |           3
 CHRISTMAS MOONSHINE         |     149 |           3
 COMA HEAD                   |     167 |           3
 CONGENIALITY QUEST          |     176 |           3
 CONTROL ANTHEM              |     182 |           3
 CONVERSATION DOWNHILL       |     183 |           3
 CREATURES SHAKESPEARE       |     189 |           3
 CURTAIN VIDEOTAPE           |     200 |           3
 CYCLONE FAMILY              |     201 |           3
 DEER VIRGINIAN              |     220 |           3
 DELIVERANCE MULHOLLAND      |     221 |           3
 DESTINATION JERK            |     225 |           3
 DETECTIVE VISION            |     228 |           3
 DRAGONFLY STRANGERS         |     251 |           3
 DUFFEL APOCALYPSE           |     261 |           3
 EARTH VISION                |     270 |           3
 EASY GLADIATOR              |     271 |           3
 EDGE KISSING                |     272 |           3
 ELIZABETH SHANE             |     279 |           3
 EXPECATIONS NATURAL         |     294 |           3
 FANTASIA PARK               |     302 |           3
 FEVER EMPIRE                |     310 |           3
 FIGHT JAWBREAKER            |     314 |           3
 FORRESTER COMANCHEROS       |     330 |           3
 FORWARD TEMPLE              |     331 |           3
 FREDDY STORM                |     334 |           3
 GALAXY SWEETHEARTS          |     346 |           3
 GARDEN ISLAND               |     350 |           3
 GATHERING CALENDAR          |     352 |           3
 GO PURPLE                   |     363 |           3
 GOSFORD DONNIE              |     371 |           3
 GREASE YOUTH                |     377 |           3
 GRIT CLOCKWORK              |     382 |           3
 HANKY OCTOBER               |     397 |           3
 HARDLY ROBBERS              |     400 |           3
 HATE HANDICAP               |     404 |           3
 HOCUS FRIDA                 |     419 |           3
 HOLY TADPOLE                |     425 |           3
 HURRICANE AFFAIR            |     443 |           3
 IMPACT ALADDIN              |     454 |           3
 IMPOSSIBLE PREJUDICE        |     455 |           3
 INFORMER DOUBLE             |     459 |           3
 INNOCENT USUAL              |     460 |           3
 ISLAND EXORCIST             |     471 |           3
 JEKYLL FROGMEN              |     481 |           3
 KISSING DOLLS               |     501 |           3
 LEBOWSKI SOLDIERS           |     514 |           3
 LION UNCUT                  |     524 |           3
 LOST BIRD                   |     533 |           3
 LOUISIANA HARRY             |     534 |           3
 MARRIED GO                  |     559 |           3
 MASKED BUBBLE               |     562 |           3
 MASSACRE USUAL              |     563 |           3
 MATRIX SNOWMAN              |     565 |           3
 MILE MULAN                  |     577 |           3
 MOCKINGBIRD HOLLYWOOD       |     586 |           3
 MOULIN WAKE                 |     601 |           3
 MUSIC BOONDOCK              |     610 |           3
 NAME DETECTIVE              |     614 |           3
 NETWORK PEAK                |     621 |           3
 OPERATION OPERATION         |     638 |           3
 PANIC CLUB                  |     653 |           3
 PAPI NECKLACE               |     656 |           3
 PAYCHECK WAIT               |     666 |           3
 POND SEATTLE                |     690 |           3
 RAGING AIRPLANE             |     711 |           3
 REIGN GENTLEMEN             |     723 |           3
 ROCKY WAR                   |     739 |           3
 ROLLERCOASTER BRINGING      |     740 |           3
 RUNAWAY TENENBAUMS          |     751 |           3
 SADDLE ANTITRUST            |     756 |           3
 SASSY PACKER                |     762 |           3
 SEABISCUIT PUNK             |     773 |           3
 SECRET GROUNDHOG            |     776 |           3
 SHANE DARKNESS              |     783 |           3
 SHOOTIST SUPERFLY           |     790 |           3
 SHREK LICENSE               |     792 |           3
 SIMON NORTH                 |     799 |           3
 SISTER FREDDY               |     801 |           3
 SLING LUKE                  |     808 |           3
 SLUMS DUCK                  |     810 |           3
 SNATCH SLIPPER              |     814 |           3
 SNOWMAN ROLLERCOASTER       |     816 |           3
 SOMETHING DUCK              |     818 |           3
 SPARTACUS CHEAPER           |     824 |           3
 SPEAKEASY DATE              |     825 |           3
 STEEL SANTA                 |     843 |           3
 STRAIGHT HOURS              |     851 |           3
 STREAK RIDGEMONT            |     855 |           3
 SUICIDES SILENCE            |     860 |           3
 SUNSET RACER                |     866 |           3
 SUPER WYOMING               |     867 |           3
 TARZAN VIDEOTAPE            |     876 |           3
 TEQUILA PAST                |     883 |           3
 TOURIST PELICAN             |     898 |           3
 TRACY CIDER                 |     901 |           3
 TRADING PINOCCHIO           |     902 |           3
 TRANSLATION SUMMER          |     907 |           3
 TURN STAR                   |     916 |           3
 TUXEDO MILE                 |     917 |           3
 TWISTED PIRATES             |     918 |           3
 UNDEFEATED DALMATIONS       |     922 |           3
 VARSITY TRIP                |     937 |           3
 VIRTUAL SPOILERS            |     946 |           3
 VOICE PEACH                 |     948 |           3
 WHISPERER GIANT             |     972 |           3
 WIND PHANTOM                |     976 |           3
 ZORRO ARK                   |    1000 |           3
 ACE GOLDFINGER              |       2 |           4
 AIRPORT POLLOCK             |       8 |           4
 ALAMO VIDEOTAPE             |      11 |           4
 ALICE FANTASIA              |      14 |           4
 ALTER VICTORY               |      18 |           4
 AMISTAD MIDSUMMER           |      22 |           4
 APACHE DIVINE               |      31 |           4
 ARIZONA BANG                |      37 |           4
 ATTACKS HATE                |      44 |           4
 ATTRACTION NEWTON           |      45 |           4
 BETRAYED REAR               |      68 |           4
 BEVERLY OUTLAW              |      69 |           4
 BIRDCAGE CASPER             |      76 |           4
 BIRDS PERDITION             |      77 |           4
 BLANKET BEVERLY             |      80 |           4
 BLOOD ARGONAUTS             |      82 |           4
 BLUES INSTINCT              |      83 |           4
 BRAVEHEART HUMAN            |      94 |           4
 BRIGHT ENCOUNTERS           |      98 |           4
 BULWORTH COMMANDMENTS       |     106 |           4
 CABIN FLASH                 |     110 |           4
 CANDIDATE PERDITION         |     116 |           4
 CASABLANCA SUPER            |     123 |           4
 CAT CONEHEADS               |     127 |           4
 CELEBRITY HORN              |     130 |           4
 CENTER DINOSAUR             |     131 |           4
 CHAMPION FLATLINERS         |     134 |           4
 CHISUM BEHAVIOR             |     145 |           4
 CINCINATTI WHISPERER        |     151 |           4
 CLERKS ANGELS               |     156 |           4
 CLUB GRAFFITI               |     160 |           4
 CLYDE THEORY                |     163 |           4
 COLDBLOODED DARLING         |     165 |           4
 COMMANDMENTS EXPRESS        |     171 |           4
 CONFESSIONS MAGUIRE         |     173 |           4
 CONSPIRACY SPIRIT           |     180 |           4
 CORE SUIT                   |     184 |           4
 CROWDS TELEMARK             |     195 |           4
 DARKO DORADO                |     210 |           4
 DATE SPEED                  |     213 |           4
 DAUGHTER MADIGAN            |     214 |           4
 DECEIVER BETRAYED           |     218 |           4
 DESPERATE TRAINSPOTTING     |     224 |           4
 DIARY PANIC                 |     230 |           4
 DISTURBING SCARFACE         |     234 |           4
 DORADO NOTTING              |     244 |           4
 DOWNHILL ENOUGH             |     247 |           4
 DREAM PICKUP                |     252 |           4
 ELEMENT FREDDY              |     276 |           4
 ENCOUNTERS CURTAIN          |     282 |           4
 ENEMY ODDS                  |     284 |           4
 ENTRAPMENT SATISFACTION     |     287 |           4
 ESCAPE METROPOLIS           |     288 |           4
 EXPENDABLE STALLION         |     295 |           4
 FALCON VOLUME               |     300 |           4
 FEUD FROGMEN                |     309 |           4
 FIDELITY DEVIL              |     313 |           4
 FLINTSTONES HAPPINESS       |     324 |           4
 FURY MURDER                 |     344 |           4
 GANGS PRIDE                 |     349 |           4
 GILBERT PELICAN             |     357 |           4
 GLASS DYING                 |     360 |           4
 GOLDFINGER SENSIBILITY      |     366 |           4
 GREEK EVERYONE              |     380 |           4
 GROSSE WONDERFUL            |     384 |           4
 GUNFIGHTER MUSSOLINI        |     389 |           4
 GUNFIGHT MOON               |     388 |           4
 HARPER DYING                |     402 |           4
 HEDWIG ALTER                |     413 |           4
 HOOK CHARIOTS               |     430 |           4
 HOPE TOOTSIE                |     432 |           4
 HOTEL HAPPINESS             |     435 |           4
 HUMAN GRAFFITI              |     438 |           4
 HUNTER ALTER                |     441 |           4
 HUSTLER PARTY               |     444 |           4
 IDENTITY LOVER              |     449 |           4
 INSECTS STONE               |     461 |           4
 ISHTAR ROCKETEER            |     470 |           4
 JEDI BENEATH                |     479 |           4
 JERICHO MULAN               |     483 |           4
 KENTUCKIAN GIANT            |     495 |           4
 LADYBUGS ARMAGEDDON         |     507 |           4
 LAWLESS VISION              |     510 |           4
 LEGEND JEDI                 |     516 |           4
 LOSE INCH                   |     531 |           4
 LOVE SUICIDES               |     535 |           4
 MADRE GABLES                |     546 |           4
 MAGIC MALLRATS              |     547 |           4
 MAGUIRE APACHE              |     550 |           4
 MOSQUITO ARMAGEDDON         |     598 |           4
 MYSTIC TRUMAN               |     613 |           4
 NATURAL STOCK               |     617 |           4
 NEWTON LABYRINTH            |     623 |           4
 OPUS ICE                    |     640 |           4
 ORIENT CLOSER               |     643 |           4
 OTHERS SOUP                 |     645 |           4
 OUTFIELD MASSACRE           |     647 |           4
 PARADISE SABRINA            |     657 |           4
 PATIENT SISTER              |     663 |           4
 PATRIOT ROMAN               |     664 |           4
 PEARL DESTINY               |     669 |           4
 PRIDE ALAMO                 |     696 |           4
 QUILLS BULL                 |     708 |           4
 RANGE MOONWALKER            |     715 |           4
 REAP UNFAITHFUL             |     716 |           4
 REEF SALUTE                 |     722 |           4
 REMEMBER DIARY              |     724 |           4
 RIVER OUTLAW                |     733 |           4
 ROUGE SQUAD                 |     746 |           4
 SABRINA MIDNIGHT            |     755 |           4
 SALUTE APOLLO               |     759 |           4
 SEARCHERS WAIT              |     774 |           4
 SHRUNK DIVINE               |     793 |           4
 SILENCE KANE                |     797 |           4
 SINNERS ATLANTIS            |     800 |           4
 SLEEPING SUSPECTS           |     804 |           4
 SLEEPLESS MONSOON           |     805 |           4
 SORORITY QUEEN              |     821 |           4
 STEERS ARMAGEDDON           |     844 |           4
 STEPMOM DREAM               |     845 |           4
 STRICTLY SCARFACE           |     857 |           4
 TIMBERLAND SKY              |     891 |           4
 TOWERS HURRICANE            |     899 |           4
 TOWN ARK                    |     900 |           4
 TRAFFIC HOBBIT              |     903 |           4
 TRAIN BUNCH                 |     904 |           4
 TRAINSPOTTING STRANGERS     |     905 |           4
 TRIP NEWTON                 |     911 |           4
 VALLEY PACKER               |     932 |           4
 VERTIGO NORTHWEST           |     939 |           4
 WARS PLUTO                  |     960 |           4
 WILD APOLLO                 |     974 |           4
 WINDOW SIDE                 |     977 |           4
 WITCHES PANIC               |     979 |           4
 WONDERFUL DROP              |     984 |           4
 WORST BANGER                |     991 |           4
 WRATH MILE                  |     992 |           4
 ADAPTATION HOLES            |       3 |           5
 AFFAIR PREJUDICE            |       4 |           5
 AFRICAN EGG                 |       5 |           5
 AIRPLANE SIERRA             |       7 |           5
 ALI FOREVER                 |      13 |           5
 ALLEY EVOLUTION             |      16 |           5
 AMERICAN CIRCUS             |      21 |           5
 ANACONDA CONFESSIONS        |      23 |           5
 ANALYZE HOOSIERS            |      24 |           5
 APOCALYPSE FLAMINGOS        |      32 |           5
 ARGONAUTS TOWN              |      36 |           5
 BARBARELLA STREETCAR        |      55 |           5
 BEAST HUNCHBACK             |      60 |           5
 BEAUTY GREASE               |      61 |           5
 BED HIGHBALL                |      62 |           5
 BEHAVIOR RUNAWAY            |      65 |           5
 BINGO TALENTED              |      73 |           5
 BLACKOUT PRIVATE            |      78 |           5
 BLADE POLISH                |      79 |           5
 BOWFINGER GABLES            |      92 |           5
 BREAKFAST GOLDFINGER        |      95 |           5
 BROOKLYN DESERT             |     100 |           5
 BROTHERHOOD BLANKET         |     101 |           5
 CASPER DRAGONFLY            |     124 |           5
 CASUALTIES ENCINO           |     126 |           5
 CATCH AMISTAD               |     128 |           5
 CHASING FIGHT               |     139 |           5
 CHILL LUCK                  |     143 |           5
 CHOCOLAT HARRY              |     147 |           5
 CIDER DESIRE                |     150 |           5
 CLOCKWORK PARADISE          |     157 |           5
 CLONES PINOCCHIO            |     158 |           5
 COMANCHEROS ENEMY           |     168 |           5
 COMFORTS RUSH               |     169 |           5
 CONTACT ANONYMOUS           |     181 |           5
 COWBOY DOOM                 |     185 |           5
 CRYSTAL BREAKING            |     198 |           5
 DADDY PITTSBURGH            |     202 |           5
 DANCES NONE                 |     205 |           5
 DAY UNFAITHFUL              |     216 |           5
 DESERT POSEIDON             |     222 |           5
 DEVIL DESIRE                |     229 |           5
 DIRTY ACE                   |     232 |           5
 DIVINE RESURRECTION         |     236 |           5
 DOUBTFIRE LABYRINTH         |     246 |           5
 DYNAMITE TARZAN             |     266 |           5
 EARRING INSTINCT            |     269 |           5
 EGG IGBY                    |     274 |           5
 EGYPT TENENBAUMS            |     275 |           5
 ELEPHANT TROJAN             |     277 |           5
 ELF MURDER                  |     278 |           5
 ENDING CROWDS               |     283 |           5
 ENGLISH BULWORTH            |     285 |           5
 EVERYONE CRAFT              |     290 |           5
 EXORCIST STING              |     293 |           5
 EYES DRIVING                |     298 |           5
 FARGO GANDHI                |     304 |           5
 FINDING ANACONDA            |     315 |           5
 FIREBALL PHILADELPHIA       |     317 |           5
 FIREHOUSE VIETNAM           |     318 |           5
 FIRE WOLVES                 |     316 |           5
 FLOATS GARDEN               |     325 |           5
 FORREST SONS                |     329 |           5
 FREAKY POCUS                |     333 |           5
 FREEDOM CLEOPATRA           |     335 |           5
 FRIDA SLIPPER               |     337 |           5
 GASLIGHT CRUSADE            |     351 |           5
 GHOST GROUNDHOG             |     354 |           5
 GONE TROUBLE                |     368 |           5
 GRAIL FRANKENSTEIN          |     375 |           5
 GRAPES FURY                 |     376 |           5
 GUN BONNIE                  |     387 |           5
 GUYS FALCON                 |     390 |           5
 HALL CASSIDY                |     392 |           5
 HAMLET WISDOM               |     394 |           5
 HAPPINESS UNITED            |     399 |           5
 HAUNTED ANTITRUST           |     405 |           5
 HAUNTING PIANIST            |     406 |           5
 HEARTBREAKERS BRIGHT        |     409 |           5
 HEAVYWEIGHTS BEAST          |     412 |           5
 HIGHBALL POTTER             |     416 |           5
 HOLOCAUST HIGHBALL          |     424 |           5
 HONEY TIES                  |     429 |           5
 HORROR REIGN                |     434 |           5
 HUNTING MUSKETEERS          |     442 |           5
 IGBY MAKER                  |     451 |           5
 INCH JET                    |     456 |           5
 INTERVIEW LIAISONS          |     465 |           5
 JASON TRAP                  |     476 |           5
 JAWBREAKER BROOKLYN         |     477 |           5
 JAWS HARRY                  |     478 |           5
 JEOPARDY ENCINO             |     482 |           5
 KANE EXORCIST               |     493 |           5
 KILL BROTHERHOOD            |     497 |           5
 KILLER INNOCENT             |     498 |           5
 KWAI HOMEWARD               |     504 |           5
 LOATHING LEGALLY            |     525 |           5
 LOSER HUSTLER               |     532 |           5
 MADISON TRAP                |     544 |           5
 MAJESTIC FLOATS             |     552 |           5
 MALLRATS UNITED             |     555 |           5
 MANNEQUIN WORST             |     558 |           5
 MILLION ACE                 |     578 |           5
 MISSION ZOOLANDER           |     583 |           5
 MODERN DORADO               |     589 |           5
 MONSOON CAUSE               |     591 |           5
 MOONSHINE CABIN             |     596 |           5
 MOTHER OLEANDER             |     599 |           5
 MULAN MOON                  |     604 |           5
 MUSCLE BRIGHT               |     609 |           5
 NEMO CAMPUS                 |     620 |           5
 NORTH TEQUILA               |     627 |           5
 OCTOBER SUBMARINE           |     633 |           5
 ODDS BOOGIE                 |     634 |           5
 ORANGE GRAPES               |     641 |           5
 OUTBREAK DIVINE             |     646 |           5
 PAJAMA JAWBREAKER           |     652 |           5
 PANTHER REDS                |     655 |           5
 PATHS CONTROL               |     662 |           5
 PEACH INNOCENT              |     667 |           5
 PEAK FOREVER                |     668 |           5
 PELICAN COMFORTS            |     670 |           5
 PERDITION FARGO             |     671 |           5
 PIANIST OUTFIELD            |     677 |           5
 PICKUP DRIVING              |     678 |           5
 PITTSBURGH HUNCHBACK        |     682 |           5
 PITY BOUND                  |     683 |           5
 PIZZA JUMANJI               |     684 |           5
 PLATOON INSTINCT            |     685 |           5
 POCUS PULP                  |     687 |           5
 PRESIDENT BANG              |     695 |           5
 PRINCESS GIANT              |     698 |           5
 PRIVATE DROP                |     699 |           5
 QUEST MUSSOLINI             |     707 |           5
 REDEMPTION COMFORTS         |     720 |           5
 REDS POCUS                  |     721 |           5
 RESURRECTION SILVERADO      |     727 |           5
 RIDGEMONT SUBMARINE         |     730 |           5
 ROBBERS JOON                |     735 |           5
 ROOF CHAMPION               |     742 |           5
 ROSES TREASURE              |     745 |           5
 ROXANNE REBEL               |     747 |           5
 RULES HUMAN                 |     749 |           5
 RUSH GOODFELLAS             |     753 |           5
 SATISFACTION CONFIDENTIAL   |     763 |           5
 SCALAWAG DUCK               |     767 |           5
 SCISSORHANDS SLUMS          |     770 |           5
 SHEPHERD MIDSUMMER          |     786 |           5
 SHINING ROSES               |     787 |           5
 SIERRA DIVIDE               |     796 |           5
 SILVERADO GOLDFINGER        |     798 |           5
 SONG HEDWIG                 |     819 |           5
 SPIRITED CASUALTIES         |     831 |           5
 SQUAD FISH                  |     836 |           5
 STAR OPERATION              |     841 |           5
 STORY SIDE                  |     850 |           5
 STRANGERS GRAFFITI          |     854 |           5
 SUGAR WONKA                 |     859 |           5
 SUIT WALLS                  |     861 |           5
 SUN CONFESSIONS             |     863 |           5
 SUNRISE LEAGUE              |     865 |           5
 SWEDEN SHINING              |     871 |           5
 SWEETHEARTS SUSPECTS        |     873 |           5
 TALENTED HOMICIDE           |     875 |           5
 TEEN APOLLO                 |     878 |           5
 TEMPLE ATTRACTION           |     881 |           5
 TENENBAUMS COMMAND          |     882 |           5
 TIGHTS DAWN                 |     890 |           5
 TOOTSIE PILOT               |     896 |           5
 TORQUE BOUND                |     897 |           5
 TREATMENT JEKYLL            |     910 |           5
 TROOPERS METAL              |     913 |           5
 UNTOUCHABLES SUNRISE        |     926 |           5
 UPRISING UPTOWN             |     927 |           5
 USUAL UNTOUCHABLES          |     929 |           5
 VAMPIRE WHALE               |     933 |           5
 VANISHING ROCKY             |     936 |           5
 VICTORY ACADEMY             |     940 |           5
 VIDEOTAPE ARSENIC           |     941 |           5
 VISION TORQUE               |     947 |           5
 VOLCANO TEXAS               |     949 |           5
 VOLUME HOUSE                |     950 |           5
 VOYAGE LEGALLY              |     951 |           5
 WAKE JAWS                   |     954 |           5
 WALLS ARTIST                |     955 |           5
 WASH HEAVENLY               |     961 |           5
 WATCH TRACY                 |     963 |           5
 WHALE BIKINI                |     971 |           5
 WOMEN DORADO                |     982 |           5
 WON DARES                   |     983 |           5
 WONDERLAND CHRISTMAS        |     985 |           5
 WORKING MICROCOSMOS         |     989 |           5
 YOUNG LANGUAGE              |     996 |           5
 YOUTH KICK                  |     997 |           5
 ZOOLANDER FICTION           |     999 |           5
 ALIEN CENTER                |      15 |           6
 AMADEUS HOLY                |      19 |           6
 AMELIE HELLFIGHTERS         |      20 |           6
 BALLOON HOMEWARD            |      51 |           6
 BANGER PINOCCHIO            |      54 |           6
 BASIC EASY                  |      57 |           6
 BEETHOVEN EXORCIST          |      64 |           6
 BILL OTHERS                 |      72 |           6
 BIRCH ANTITRUST             |      74 |           6
 BOOGIE AMELIE               |      86 |           6
 BREAKING HOME               |      96 |           6
 BUCKET BROTHERHOOD          |     103 |           6
 CANYON STOCK                |     118 |           6
 CAUSE DATE                  |     129 |           6
 CHANCE RESURRECTION         |     135 |           6
 CHAPLIN LICENSE             |     136 |           6
 CLOSER BANG                 |     159 |           6
 CLUE GRAIL                  |     161 |           6
 CONFUSED CANDLES            |     175 |           6
 CONQUERER NUTS              |     179 |           6
 CRAFT OUTFIELD              |     186 |           6
 CRANES RESERVOIR            |     187 |           6
 CREEPERS KANE               |     190 |           6
 CROOKED FROGMEN             |     191 |           6
 DALMATIONS SWEDEN           |     204 |           6
 DANCING FEVER               |     206 |           6
 DAWN POND                   |     215 |           6
 DAZED PUNK                  |     217 |           6
 DINOSAUR SECRETARY          |     231 |           6
 DIVIDE MONSTER              |     235 |           6
 DIVORCE SHINING             |     237 |           6
 DOCTOR GRAIL                |     238 |           6
 DOZEN LION                  |     248 |           6
 EAGLES PANKY                |     267 |           6
 EARLY HOME                  |     268 |           6
 ENCINO ELF                  |     281 |           6
 EVE RESURRECTION            |     289 |           6
 EVOLUTION ALTER             |     291 |           6
 FACTORY DRAGON              |     299 |           6
 FATAL HAUNTED               |     305 |           6
 FROGMEN BREAKING            |     339 |           6
 FRONTIER CABIN              |     340 |           6
 FULL FLATLINERS             |     343 |           6
 GILMORE BOILED              |     358 |           6
 GLADIATOR WESTWARD          |     359 |           6
 GLORY TRACY                 |     362 |           6
 GODFATHER DIARY             |     364 |           6
 GRACELAND DYNAMITE          |     372 |           6
 GRAFFITI LOVE               |     374 |           6
 GREATEST NORTH              |     378 |           6
 GRINCH MASSAGE              |     381 |           6
 GUMP DATE                   |     386 |           6
 HALF OUTFIELD               |     391 |           6
 HARRY IDAHO                 |     403 |           6
 HEAVENLY GUN                |     411 |           6
 HILLS NEIGHBORS             |     417 |           6
 HOLIDAY GAMES               |     421 |           6
 HOLLYWOOD ANONYMOUS         |     423 |           6
 HOME PITY                   |     426 |           6
 HOURS RAGE                  |     436 |           6
 HYDE DOCTOR                 |     445 |           6
 ICE CROSSING                |     447 |           6
 IDAHO LOVE                  |     448 |           6
 INTOLERABLE INTENTIONS      |     466 |           6
 JEEPERS WEDDING             |     480 |           6
 JET NEIGHBORS               |     486 |           6
 JUMANJI BLADE               |     490 |           6
 JUNGLE CLOSER               |     492 |           6
 KICK SAVANNAH               |     496 |           6
 KING EVOLUTION              |     499 |           6
 KNOCK WARLOCK               |     502 |           6
 LABYRINTH LEAGUE            |     505 |           6
 LANGUAGE COWBOY             |     509 |           6
 LEAGUE HELLFIGHTERS         |     512 |           6
 LEGALLY SECRETARY           |     515 |           6
 LIAISONS SWEET              |     518 |           6
 LOLA AGENT                  |     527 |           6
 LORD ARIZONA                |     530 |           6
 LOVELY JINGLE               |     536 |           6
 LUCK OPUS                   |     539 |           6
 MADIGAN DORADO              |     543 |           6
 MAUDE MOD                   |     566 |           6
 MEET CHOCOLATE              |     567 |           6
 MEMENTO ZOOLANDER           |     568 |           6
 MERMAID INSECTS             |     570 |           6
 METROPOLIS COMA             |     572 |           6
 MICROCOSMOS PARADISE        |     573 |           6
 MINDS TRUMAN                |     579 |           6
 MIXED DOORS                 |     584 |           6
 MOB DUFFEL                  |     585 |           6
 MOD SECRETARY               |     587 |           6
 MONTEREY LABYRINTH          |     593 |           6
 MULHOLLAND BEAST            |     605 |           6
 NONE SPIKING                |     625 |           6
 NOON PAPI                   |     626 |           6
 NOVOCAINE FLIGHT            |     631 |           6
 OPPOSITE NECKLACE           |     639 |           6
 OSCAR GOLD                  |     644 |           6
 PARIS WEEKEND               |     658 |           6
 PARK CITIZEN                |     659 |           6
 PAST SUICIDES               |     661 |           6
 PERFECT GROOVE              |     672 |           6
 POLLOCK DELIVERANCE         |     689 |           6
 POSEIDON FOREVER            |     691 |           6
 POTLUCK MIXED               |     692 |           6
 QUEEN LUKE                  |     706 |           6
 RACER EGG                   |     709 |           6
 RAIDERS ANTITRUST           |     712 |           6
 RAINBOW SHOCK               |     713 |           6
 REBEL AIRPORT               |     718 |           6
 RUGRATS SHAKESPEARE         |     748 |           6
 RUN PACIFIC                 |     750 |           6
 SANTA PARIS                 |     761 |           6
 SAVANNAH TOWN               |     766 |           6
 SEATTLE EXPECATIONS         |     775 |           6
 SECRETARY ROUGE             |     777 |           6
 SECRETS PARADISE            |     778 |           6
 SENSIBILITY REAR            |     780 |           6
 SHAKESPEARE SADDLE          |     782 |           6
 SIDE ARK                    |     794 |           6
 SLEEPY JAPANESE             |     806 |           6
 SMOKING BARBARELLA          |     812 |           6
 SONS INTERVIEW              |     820 |           6
 SPEED SUIT                  |     826 |           6
 SPIKING ELEMENT             |     828 |           6
 STAGECOACH ARMAGEDDON       |     838 |           6
 STAMPEDE DISTURBING         |     840 |           6
 SWARM GOLD                  |     870 |           6
 SWEET BROTHERHOOD           |     872 |           6
 TAXI KICK                   |     877 |           6
 TEXAS WATCH                 |     885 |           6
 THEORY MERMAID              |     886 |           6
 TIES HUNGER                 |     889 |           6
 TOMORROW HUSTLER            |     895 |           6
 TRAMP OTHERS                |     906 |           6
 TRUMAN CRAZY                |     915 |           6
 TYCOON GATHERING            |     919 |           6
 UNITED PILOT                |     925 |           6
 VACATION BOONDOCK           |     930 |           6
 WAGON JAWS                  |     952 |           6
 WARLOCK WEREWOLF            |     959 |           6
 WASTELAND DIVINE            |     962 |           6
 WATERFRONT DELIVERANCE      |     964 |           6
 WATERSHIP FRONTIER          |     965 |           6
 WESTWARD SEABISCUIT         |     970 |           6
 WIFE TURN                   |     973 |           6
 WOLVES DESIRE               |     981 |           6
 WORDS HUNTER                |     987 |           6
 WYOMING STORM               |     994 |           6
 ZHIVAGO CORE                |     998 |           6
 AGENT TRUMAN                |       6 |           7
 ALASKA PHANTOM              |      12 |           7
 ANTITRUST TOMATOES          |      29 |           7
 ARMAGEDDON LOST             |      39 |           7
 ARMY FLINTSTONES            |      40 |           7
 ARTIST COLDBLOODED          |      42 |           7
 BACKLASH UNDEFEATED         |      48 |           7
 BALLROOM MOCKINGBIRD        |      52 |           7
 BANG KWAI                   |      53 |           7
 BEACH HEARTBREAKERS         |      58 |           7
 BEDAZZLED MARRIED           |      63 |           7
 BENEATH RUSH                |      66 |           7
 BORROWERS BEDAZZLED         |      89 |           7
 BUTTERFLY CHOCOLAT          |     109 |           7
 CADDYSHACK JEDI             |     111 |           7
 CANDLES GRAPES              |     117 |           7
 CAPER MOTIONS               |     119 |           7
 CAROL TEXAS                 |     121 |           7
 CARRIE BUNCH                |     122 |           7
 CASSIDY WYOMING             |     125 |           7
 CHAMBER ITALIAN             |     133 |           7
 CHOCOLATE DUCK              |     148 |           7
 CLASH FREDDY                |     154 |           7
 CLEOPATRA DEVIL             |     155 |           7
 COLOR PHILADELPHIA          |     166 |           7
 CONNECTICUT TRAMP           |     177 |           7
 CONNECTION MICROCOSMOS      |     178 |           7
 DAISY MENAGERIE             |     203 |           7
 DEEP CRUSADE                |     219 |           7
 DESIRE ALIEN                |     223 |           7
 DESTINY SATURDAY            |     226 |           7
 DISCIPLE MOTHER             |     233 |           7
 DOGMA FAMILY                |     239 |           7
 DONNIE ALLEY                |     241 |           7
 DRIFTER COMMANDMENTS        |     253 |           7
 DRIVING POLISH              |     255 |           7
 DRUMS DYNAMITE              |     258 |           7
 DUDE BLINDNESS              |     260 |           7
 EFFECT GLADIATOR            |     273 |           7
 EXTRAORDINARY CONQUERER     |     297 |           7
 FELLOWSHIP AUTUMN           |     307 |           7
 FLASH WARS                  |     321 |           7
 FRENCH HOLIDAY              |     336 |           7
 FROST HEAD                  |     341 |           7
 GOLDMINE TYCOON             |     367 |           7
 GORGEOUS BINGO              |     370 |           7
 GROOVE FICTION              |     383 |           7
 GROUNDHOG UNCUT             |     385 |           7
 HALLOWEEN NUTS              |     393 |           7
 HANDICAP BOONDOCK           |     395 |           7
 HANGING DEEP                |     396 |           7
 HANOVER GALAXY              |     398 |           7
 HAROLD FRENCH               |     401 |           7
 HAWK CHILL                  |     407 |           7
 HIGH ENCINO                 |     415 |           7
 HOMEWARD CIDER              |     427 |           7
 ILLUSION AMELIE             |     452 |           7
 INTRIGUE WORST              |     467 |           7
 INVASION CYCLONE            |     468 |           7
 KISS GLORY                  |     500 |           7
 LEATHERNECKS DWARFS         |     513 |           7
 LIBERTY MAGNIFICENT         |     519 |           7
 LIES TREATMENT              |     521 |           7
 LOVER TRUMAN                |     537 |           7
 LUST LOCK                   |     542 |           7
 MADNESS ATTACKS             |     545 |           7
 MAGNIFICENT CHITTY          |     548 |           7
 MAGNOLIA FORRESTER          |     549 |           7
 MALKOVICH PET               |     554 |           7
 MARS ROMAN                  |     560 |           7
 MONEY HAROLD                |     590 |           7
 MONSTER SPARTACUS           |     592 |           7
 MOONWALKER FOOL             |     597 |           7
 MOURNING PURPLE             |     602 |           7
 MUSSOLINI SPOILERS          |     612 |           7
 NASH CHOCOLAT               |     615 |           7
 NATIONAL STORY              |     616 |           7
 NEIGHBORS CHARADE           |     619 |           7
 ORDER BETRAYED              |     642 |           7
 OUTLAW HANKY                |     648 |           7
 PET HAUNTING                |     674 |           7
 PILOT HOOSIERS              |     679 |           7
 PLUTO OLEANDER              |     686 |           7
 POTTER CONNECTICUT          |     693 |           7
 PRIMARY GLASS               |     697 |           7
 PRIX UNDEFEATED             |     700 |           7
 PULP BEVERLY                |     702 |           7
 PUNK DIVORCE                |     703 |           7
 RAGE GAMES                  |     710 |           7
 REUNION WITCHES             |     728 |           7
 RIGHT CRANES                |     731 |           7
 ROCKETEER MOTHER            |     738 |           7
 RUSHMORE MERMAID            |     754 |           7
 SAGEBRUSH CLUELESS          |     757 |           7
 SCARFACE BANG               |     768 |           7
 SENSE GREEK                 |     779 |           7
 SEVEN SWARM                 |     781 |           7
 SIEGE MADRE                 |     795 |           7
 SLEUTH ORIENT               |     807 |           7
 SLIPPER FIDELITY            |     809 |           7
 SPOILERS HELLFIGHTERS       |     834 |           7
 STALLION SUNDANCE           |     839 |           7
 STATE WASTELAND             |     842 |           7
 STING PERSONAL              |     846 |           7
 STOCK GLASS                 |     847 |           7
 STREETCAR INTENTIONS        |     856 |           7
 SUNDANCE INVASION           |     864 |           7
 SUPERFLY TRIP               |     868 |           7
 TELEGRAPH VOYAGE            |     879 |           7
 THIEF PELICAN               |     887 |           7
 TITANS JERK                 |     893 |           7
 TRAP GUYS                   |     908 |           7
 TREASURE COMMAND            |     909 |           7
 UNCUT SUICIDES              |     921 |           7
 UNFORGIVEN ZOOLANDER        |     924 |           7
 UPTOWN YOUNG                |     928 |           7
 WANDA CHAMBER               |     956 |           7
 WEREWOLF LOLA               |     968 |           7
 WISDOM WORKER               |     978 |           7
 ALADDIN CALENDAR            |      10 |           8
 ALONE TRIP                  |      17 |           8
 APOLLO TEEN                 |      33 |           8
 ARACHNOPHOBIA ROLLERCOASTER |      35 |           8
 BABY HALL                   |      47 |           8
 BADMAN DAWN                 |      49 |           8
 BAREFOOT MANCHURIAN         |      56 |           8
 BOILED DARES                |      84 |           8
 BOULEVARD MOB               |      90 |           8
 BULL SHAWSHANK              |     105 |           8
 BUNCH MINDS                 |     107 |           8
 CALENDAR GUNFIGHT           |     112 |           8
 CARIBBEAN LIBERTY           |     120 |           8
 CHICAGO NORTH               |     141 |           8
 CITIZEN SHREK               |     153 |           8
 CLUELESS BUCKET             |     162 |           8
 COMMAND DARLING             |     170 |           8
 CROSSROADS CASUALTIES       |     193 |           8
 CUPBOARD SINNERS            |     199 |           8
 DANGEROUS UPTOWN            |     207 |           8
 DOOM DANCING                |     242 |           8
 DOUBLE WRATH                |     245 |           8
 DRAGON SQUAD                |     250 |           8
 DRIVER ANNIE                |     254 |           8
 DROP WATERFRONT             |     256 |           8
 EXCITEMENT EVE              |     292 |           8
 EXPRESS LONELY              |     296 |           8
 FICTION CHRISTMAS           |     311 |           8
 FLYING HOOK                 |     326 |           8
 GABLES METROPOLIS           |     345 |           8
 GAMES BOWFINGER             |     347 |           8
 GANDHI KWAI                 |     348 |           8
 GENTLEMEN STAGE             |     353 |           8
 GLEAMING JAWBREAKER         |     361 |           8
 GOODFELLAS SALUTE           |     369 |           8
 GREEDY ROOTS                |     379 |           8
 HOBBIT ALIEN                |     418 |           8
 HOMICIDE PEACH              |     428 |           8
 HORN WORKING                |     433 |           8
 IDOLS SNATCHERS             |     450 |           8
 IRON MOON                   |     469 |           8
 JADE BUNCH                  |     474 |           8
 JERK PAYCHECK               |     484 |           8
 JUMPING WRATH               |     491 |           8
 KARATE MOON                 |     494 |           8
 KRAMER CHOCOLATE            |     503 |           8
 LADY STAGE                  |     506 |           8
 LICENSE WEEKEND             |     520 |           8
 LIFE TWISTED                |     522 |           8
 MAIDEN HOME                 |     551 |           8
 METAL ARMAGEDDON            |     571 |           8
 MIGHTY LUCK                 |     576 |           8
 MODEL FISH                  |     588 |           8
 MOTIONS DETAILS             |     600 |           8
 MOVIE SHAKESPEARE           |     603 |           8
 MUPPET MILE                 |     607 |           8
 MURDER ANTITRUST            |     608 |           8
 NECKLACE OUTBREAK           |     618 |           8
 NEWSIES STORY               |     622 |           8
 NORTHWEST POLISH            |     628 |           8
 PACIFIC AMISTAD             |     650 |           8
 PANKY SUBMARINE             |     654 |           8
 PURPLE MOVIE                |     705 |           8
 REAR TRADING                |     717 |           8
 RECORDS ZORRO               |     719 |           8
 REQUIEM TYCOON              |     725 |           8
 RESERVOIR ADAPTATION        |     726 |           8
 ROAD ROXANNE                |     734 |           8
 ROCK INSTINCT               |     737 |           8
 RUNNER MADIGAN              |     752 |           8
 SCHOOL JACKET               |     769 |           8
 SCORPION APOLLO             |     771 |           8
 SEA VIRGIN                  |     772 |           8
 SHANGHAI TYCOON             |     784 |           8
 SHIP WONDERLAND             |     788 |           8
 SMILE EARRING               |     811 |           8
 SPINAL ROCKY                |     829 |           8
 SPY MILE                    |     835 |           8
 STORM HAPPINESS             |     849 |           8
 SUMMER SCARFACE             |     862 |           8
 SUSPECTS QUILLS             |     869 |           8
 TADPOLE PARK                |     874 |           8
 TROJAN TOMORROW             |     912 |           8
 TROUBLE DATE                |     914 |           8
 UNBREAKABLE KARATE          |     920 |           8
 UNFAITHFUL KILL             |     923 |           8
 VIRGIN DAISY                |     944 |           8
 VIRGINIAN PLUTO             |     945 |           8
 WARDROBE PHANTOM            |     958 |           8
 WORLD LEATHERNECKS          |     990 |           8
 ALABAMA DEVIL               |       9 |           9
 ANGELS LIFE                 |      25 |           9
 ANONYMOUS HUMAN             |      27 |           9
 ATLANTIS CAUSE              |      43 |           9
 BONNIE HOLOCAUST            |      85 |           9
 BORN SPINAL                 |      88 |           9
 CONEHEADS SMOOCHY           |     172 |           9
 CRUSADE HONEY               |     197 |           9
 DARN FORRESTER              |     212 |           9
 DOORS PRESIDENT             |     243 |           9
 DUMBO LUST                  |     262 |           9
 DURHAM PANKY                |     263 |           9
 EMPIRE MALKOVICH            |     280 |           9
 ENOUGH RAGING               |     286 |           9
 FAMILY SWEET                |     301 |           9
 FANTASY TROOPERS            |     303 |           9
 FEATHERS METAL              |     306 |           9
 FLAMINGOS CONNECTICUT       |     320 |           9
 FLATLINERS KILLER           |     322 |           9
 FRISCO FORREST              |     338 |           9
 HOUSE DYNAMITE              |     437 |           9
 HYSTERICAL GRAIL            |     446 |           9
 INDEPENDENCE HOTEL          |     457 |           9
 INSIDER ARIZONA             |     462 |           9
 JAPANESE RUN                |     475 |           9
 JERSEY SASSY                |     485 |           9
 JUGGLER HARDLY              |     489 |           9
 LOVERBOY ATTACKS            |     538 |           9
 LUKE MUMMY                  |     541 |           9
 MASSAGE IMAGE               |     564 |           9
 MIDNIGHT WESTWARD           |     574 |           9
 OKLAHOMA JUMANJI            |     635 |           9
 OPEN AFRICAN                |     637 |           9
 PATTON INTERVIEW            |     665 |           9
 PERSONAL LADYBUGS           |     673 |           9
 RIDER CADDYSHACK            |     729 |           9
 SATURDAY LAMBS              |     764 |           9
 SNATCHERS MONTEZUMA         |     815 |           9
 SOLDIERS EVOLUTION          |     817 |           9
 STRANGELOVE DESIRE          |     852 |           9
 STRANGER STRANGERS          |     853 |           9
 TOMATOES HELLFIGHTERS       |     894 |           9
 VELVET TERMINATOR           |     938 |           9
 WAIT CIDER                  |     953 |           9
 WAR NOTTING                 |     957 |           9
 WEST LION                   |     969 |           9
 WIZARD COLDBLOODED          |     980 |           9
 WORKER TARZAN               |     988 |           9
 WRONG BEHAVIOR              |     993 |           9
 ACADEMY DINOSAUR            |       1 |          10
 BERETS AGENT                |      67 |          10
 CHINATOWN GLADIATOR         |     144 |          10
 COAST RAINBOW               |     164 |          10
 CROW GREASE                 |     194 |          10
 DARES PLUTO                 |     208 |          10
 HEAVEN FREEDOM              |     410 |          10
 HOOSIERS BIRDCAGE           |     431 |          10
 INDIAN LOVE                 |     458 |          10
 JACKET FRISCO               |     473 |          10
 LUCKY FLYING                |     540 |          10
 OLEANDER CLUE               |     636 |          10
 POLISH BROOKLYN             |     688 |          10
 PREJUDICE OLEANDER          |     694 |          10
 ROOTS REMEMBER              |     744 |          10
 SAINTS BRIDE                |     758 |          10
 SHAWSHANK BUBBLE            |     785 |          10
 SPLASH GUMP                 |     832 |          10
 SPLENDOR PATTON             |     833 |          10
 WEDDING APOLLO              |     966 |          10
 WEEKEND PERSONAL            |     967 |          10
 FIDDLER LOST                |     312 |          11
 FUGITIVE MAGUIRE            |     342 |          11
 HOLES BRANNIGAN             |     420 |          11
 IMAGE PRINCESS              |     453 |          11
 INSTINCT AIRPORT            |     463 |          11
 MAKER GABLES                |     553 |          11
 MASK PEACH                  |     561 |          11
 OZ LIAISONS                 |     649 |          11
 PINOCCHIO SIMON             |     680 |          11
 RINGS HEARTBREAKERS         |     732 |          11
 SPICE SORORITY              |     827 |          11
 SPIRIT FLINTSTONES          |     830 |          11
 SUBMARINE BED               |     858 |          11
 TELEMARK HEARTBREAKERS      |     880 |          11
 ARABIA DOGMA                |      34 |          12
 HELLFIGHTERS SIERRA         |     414 |          12
 LESSON CLEOPATRA            |     517 |          12
 LONELY ELEPHANT             |     529 |          12
 SKY MIRACLE                 |     802 |          12
 TITANIC BOONDOCK            |     892 |          12
 BOONDOCK BALLROOM           |      87 |          13
 CHITTY LOCK                 |     146 |          13
 CRAZY HOME                  |     188 |          13
 DRACULA CRYSTAL             |     249 |          13
 MUMMY CREATURES             |     606 |          13
 RANDOM GO                   |     714 |          13
 LAMBS CINCINATTI            |     508 |          15
(997 rows)
